#pragma once

#include <Arduino.h>

#define FW_DEVICE_NAME "OST-RSP"

#define FW_PIN_RF_DATA 26
#define FW_PIN_PUMP_OUT 25
#define FW_PIN_VALVE_OUT 17
#define FW_PIN_PRESSURE_ANALOG 34

#define FW_OUTPUT_ACTIVE_LEVEL HIGH
#define FW_OUTPUT_INACTIVE_LEVEL LOW
#define FW_PUMP_PWM_FREQUENCY_HZ 20000UL
#define FW_PUMP_PWM_RESOLUTION_BITS 10
#define FW_PUMP_PWM_MAX_DUTY 1023UL

#define FW_ADC_REFERENCE_MV 3300L
#define FW_ADC_MAX_COUNTS 4095L
#define FW_SENSOR_ZERO_MV 2500L
#define FW_SENSOR_MV_PER_HPA 2L
#define FW_DEFAULT_DIVIDER_MULTIPLIER_X1000 1515L
#define FW_DEFAULT_PRESSURE_DEADZONE_HPA 50L
#define FW_MIN_PRESSURE_DEADZONE_HPA 0L
#define FW_MAX_PRESSURE_DEADZONE_HPA 1000L

#define FW_ADAPTIVE_PID_KP_X1000 1800L
#define FW_ADAPTIVE_PID_KI_X1000 35L
#define FW_ADAPTIVE_PID_KD_X1000 250L
#define FW_ADAPTIVE_PID_MAX_INTEGRAL_HPA_MS 600000L
#define FW_ADAPTIVE_RESPONSE_MIN_X1000 100L
#define FW_ADAPTIVE_RESPONSE_START_X1000 2000L

#define FW_DEFAULT_MAX_SESSION_SECONDS 28800UL
#define FW_DEFAULT_MAX_PUMPING_SECONDS 1500UL
#define FW_LOOP_PERIOD_MS 50UL
#define FW_RF_DEBOUNCE_MS 1000UL
#define FW_TASK_WATCHDOG_TIMEOUT_MS 15000UL

#define FW_RF_BUTTON_A_CODES_COUNT 2
#define FW_RF_BUTTON_B_CODES_COUNT 2

static const unsigned long FW_RF_BUTTON_A_CODES[FW_RF_BUTTON_A_CODES_COUNT] = {
    4649217UL,
    7300524UL
};

static const unsigned long FW_RF_BUTTON_B_CODES[FW_RF_BUTTON_B_CODES_COUNT] = {
    4649218UL,
    7300528UL
};
